# Customer Churn Predictor

### Business Understanding

#### **Problem Statement** 

#### Stakeholder:
     - 
     - 
     - 
#### **Key Metrics and Success Criteria**
     -The Model should have an accuracy score of 85% (On balanced data)
     -Good models are expected to have an accuracy score of >0.80 or 80%
     -An ROC Curve of 80% or 0.80 is ideal for the model to generate well 
     -There should be atleast 4 baseline models 
     -All hyperparameter tuning should only be applied if it exceed it F1 score 

#### Features
    - customerID- Unique Customer Identifuication 
    - gender-
    - SeniorCitizen
    - Partner
    - Dependents
    - tenure
    -PhoneService 
    - MultipleLines
    - InternetService
    - OnlineSecurity
    - OnlineBackup
    - DeviceProtection
    - TechSupport
    - StreamingTV
    - StreamingMovies
    - Contract
    - PaperlessBilling
    - PaymentMethod
    - MonthlyCharges
    - TotalCharges
    - Churn

#### **Null Hypothesis**

#### **Alternative Hpothesis**


#### Analytical Questions
    1. What is the Churn percentage based on
    2. 
    3.
    4.


    
    


### Data Understanding

#### **Importations**

In [1]:
# Data Manipulation Packages 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import pyodbc
from dotenv import dotenv_values
import warnings
warnings.filterwarnings('ignore')


#### **Load Datasets**

In [2]:
# Load environment variables from .env file into a dictionary
environment_variables = dotenv_values (r'C:\Users\Admin\OneDrive\OneDrive-Azubi\Customer-Churn-Prediction-\.env')

# Get the values for the credentials you set in the '.env' file
server = environment_variables.get('SERVER')
database = environment_variables.get('DATABASE')
username = environment_variables.get('USERNAME')
password = environment_variables.get('PASSWORD')

# Create a connection string
connection_string = f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password};MARS_Connection=yes;MinProtocolVersion=TLSv1.2;"


connection = pyodbc.connect(connection_string)

In [4]:
# Loading the First 3000 dataset
query = "SELECT * FROM LP2_Telco_churn_first_3000"

data = pd.read_sql(query, connection)

data.head()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  7590-VHVEG  Female          False     True       False       1   
1  5575-GNVDE    Male          False    False       False      34   
2  3668-QPYBK    Male          False    False       False       2   
3  7795-CFOCW    Male          False    False       False      45   
4  9237-HQITU  Female          False    False       False       2   

   PhoneService MultipleLines InternetService OnlineSecurity  ...  \
0         False          None             DSL          False  ...   
1          True         False             DSL           True  ...   
2          True         False             DSL           True  ...   
3         False          None             DSL           True  ...   
4          True         False     Fiber optic          False  ...   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0            False       False       False           False  Month-to-month   
1             True       False       False           False        One year   
2            False       False       False           False  Month-to-month   
3             True        True       False           False        One year   
4            False       False       False           False  Month-to-month   

  PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0             True           Electronic check      29.850000     29.850000   
1            False               Mailed check      56.950001   1889.500000   
2             True               Mailed check      53.849998    108.150002   
3            False  Bank transfer (automatic)      42.299999   1840.750000   
4             True           Electronic check      70.699997    151.649994   

   Churn  
0  False  
1  False  
2   True  
3  False  
4   True  

[5 rows x 21 columns]

In [12]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [10]:
# Loading the second 2000 data
df=pd.read_csv('../data/LP2_Telco-churn-second-2000.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  5600-PDUJF    Male              0      No         No       6          Yes   
1  8292-TYSPY    Male              0      No         No      19          Yes   
2  0567-XRHCU  Female              0     Yes        Yes      69           No   
3  1867-BDVFH    Male              0     Yes        Yes      11          Yes   
4  2067-QYTCF  Female              0     Yes         No      64          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0                No             DSL             No  ...               No   
1                No             DSL             No  ...              Yes   
2  No phone service             DSL            Yes  ...              Yes   
3               Yes     Fiber optic             No  ...               No   
4               Yes     Fiber optic             No  ...              Yes   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0         Yes          No              No  Month-to-month              Yes   
1         Yes          No              No  Month-to-month              Yes   
2          No          No             Yes        Two year              Yes   
3          No          No              No  Month-to-month              Yes   
4         Yes         Yes             Yes  Month-to-month              Yes   

             PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Credit card (automatic)          49.50         312.7    No  
1  Credit card (automatic)          55.00        1046.5   Yes  
2  Credit card (automatic)          43.95        2960.1    No  
3         Electronic check          74.35         834.2   Yes  
4         Electronic check         111.15        6953.4    No  

[5 rows x 21 columns]

In [11]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

#### **Merge the Train Datasets**

In [16]:
# Combine DataFrames
churn_train = pd.concat([data, df], ignore_index=True)

churn_train

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0    True      False       1   
1     5575-GNVDE    Male              0   False      False      34   
2     3668-QPYBK    Male              0   False      False       2   
3     7795-CFOCW    Male              0   False      False      45   
4     9237-HQITU  Female              0   False      False       2   
...          ...     ...            ...     ...        ...     ...   
5038  6840-RESVB    Male              0     Yes        Yes      24   
5039  2234-XADUH  Female              0     Yes        Yes      72   
5040  4801-JZAZL  Female              0     Yes        Yes      11   
5041  8361-LTMKD    Male              1     Yes         No       4   
5042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0           False              None             DSL          False  ...   
1            True             False             DSL           True  ...   
2            True             False             DSL           True  ...   
3           False              None             DSL           True  ...   
4            True             False     Fiber optic          False  ...   
...           ...               ...             ...            ...  ...   
5038          Yes               Yes             DSL            Yes  ...   
5039          Yes               Yes     Fiber optic             No  ...   
5040           No  No phone service             DSL            Yes  ...   
5041          Yes               Yes     Fiber optic             No  ...   
5042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               False       False       False           False  Month-to-month   
1                True       False       False           False        One year   
2               False       False       False           False  Month-to-month   
3                True        True       False           False        One year   
4               False       False       False           False  Month-to-month   
...               ...         ...         ...             ...             ...   
5038              Yes         Yes         Yes             Yes        One year   
5039              Yes          No         Yes             Yes        One year   
5040               No          No          No              No  Month-to-month   
5041               No          No          No              No  Month-to-month   
5042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                True           Electronic check      29.850000         29.85   
1               False               Mailed check      56.950001        1889.5   
2                True               Mailed check      53.849998    108.150002   
3               False  Bank transfer (automatic)      42.299999       1840.75   
4                True           Electronic check      70.699997    151.649994   
...               ...                        ...            ...           ...   
5038              Yes               Mailed check      84.800000        1990.5   
5039              Yes    Credit card (automatic)     103.200000        7362.9   
5040              Yes           Electronic check      29.600000        346.45   
5041              Yes               Mailed check      74.400000         306.6   
5042              Yes  Bank transfer (automatic)     105.650000        6844.5   

      Churn  
0     False  
1     False  
2      True  
3     False  
4      True  
...     ...  
5038     No  
5039     No  
5040     No  
5041    Yes  
5042     No  

[5043 rows x 21 columns]

In [14]:
churn_train.shape

(5043, 21)

In [15]:
churn_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        5043 non-null   object 
 1   gender            5043 non-null   object 
 2   SeniorCitizen     5043 non-null   int64  
 3   Partner           5043 non-null   object 
 4   Dependents        5043 non-null   object 
 5   tenure            5043 non-null   int64  
 6   PhoneService      5043 non-null   object 
 7   MultipleLines     4774 non-null   object 
 8   InternetService   5043 non-null   object 
 9   OnlineSecurity    4392 non-null   object 
 10  OnlineBackup      4392 non-null   object 
 11  DeviceProtection  4392 non-null   object 
 12  TechSupport       4392 non-null   object 
 13  StreamingTV       4392 non-null   object 
 14  StreamingMovies   4392 non-null   object 
 15  Contract          5043 non-null   object 
 16  PaperlessBilling  5043 non-null   object 


In [18]:
churn_train ['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [19]:
churn_train ['SeniorCitizen'].unique()

array([0, 1], dtype=int64)

In [20]:
churn_train ['Partner'].unique()

array([True, False, 'No', 'Yes'], dtype=object)

In [22]:
churn_train ['Dependents'].unique()

array([False, True, 'No', 'Yes'], dtype=object)

In [23]:
churn_train ['tenure'].unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39], dtype=int64)

In [24]:
churn_train ['PhoneService'].unique()

array([False, True, 'Yes', 'No'], dtype=object)

In [25]:
churn_train ['MultipleLines'].unique()

array([None, False, True, 'No', 'No phone service', 'Yes'], dtype=object)

In [26]:
churn_train ['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [27]:
churn_train ['OnlineSecurity'].unique()

array([False, True, None, 'No', 'Yes', 'No internet service'],
      dtype=object)

In [28]:
churn_train ['OnlineBackup'].unique()

array([True, False, None, 'No', 'Yes', 'No internet service'],
      dtype=object)

In [29]:
churn_train ['DeviceProtection'].unique()

array([False, True, None, 'No', 'Yes', 'No internet service'],
      dtype=object)

In [30]:
churn_train ['TechSupport'].unique()

array([False, True, None, 'Yes', 'No', 'No internet service'],
      dtype=object)

In [31]:
churn_train ['StreamingTV'].unique()

array([False, True, None, 'No', 'Yes', 'No internet service'],
      dtype=object)

In [32]:
churn_train ['StreamingMovies'].unique()

array([False, True, None, 'No', 'Yes', 'No internet service'],
      dtype=object)

In [33]:
churn_train ['Contract'].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [34]:
churn_train ['PaperlessBilling'].unique()

array([True, False, 'Yes', 'No'], dtype=object)

In [35]:
churn_train ['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [36]:
churn_train ['MonthlyCharges'].unique()

array([ 29.85000038,  56.95000076,  53.84999847, ...,  78.7       ,
        60.65      , 103.2       ])

In [37]:
churn_train ['TotalCharges'].unique()

array([29.850000381469727, 1889.5, 108.1500015258789, ..., '346.45',
       '306.6', '6844.5'], dtype=object)

In [38]:
churn_train ['Churn'].unique()

array([False, True, None, 'No', 'Yes'], dtype=object)

#### Key Insights 
    - Rename the column names 
    - Why is senior citizens in 0 and 1 and what does it mean
    - most column have true and false, yes and no and, other top it, no internet service what is this supposed to mean
    - Monthlycharge and total charge column look funny
    - Total charges column should be a float datatype

### Data Preparation

### Modeling And Evaluation